spring.application.name=fyp
spring.datasource.url=jdbc:postgresql://35.246.42.56:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Dormezzled79!
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=Mz9jk2nWq8S45p0bRHT28FvhqWkLE9tu0dPlAs37YxQbVm4C1rSdNf8GhJkQwZe
