spring.application.name=fyp
spring.datasource.url=jdbc:postgresql://35.246.42.56:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=FYP_connect10
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${JWT_SECRET:LXP2vP/iOOfIgFT/pthYQtyZGmQNXoRPRmbZMXKwKbQ=}